name: Load secrets
inputs:
  stack:
    type: choice
    description: 'The stack to run the job on (go, npm, all, none)'
    default: none
    options:
      - go
      - npm
      - all
      - none
  app-pk:
    required: true
  app-id:
    required: true
outputs:
  token:
    value: ${{ steps.botanibit.outputs.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/create-github-app-token@v1
      id: botanibit
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pk }}
        owner: ${{ github.repository_owner }}

    - name: Set up Git name and email
      shell: bash
      run: |
        git config --global user.name "botanibit[bot]"
        git config --global user.email ${{ inputs.app-id }}+botanibit[bot]@users.noreply.github.com

    - name: Set up Git with token for private go dependencies
      shell: bash
      if: ${{ inputs.stack == 'go' || inputs.stack == 'all' }}
      run: |
        git config --global url."https://x-access-token:${{ steps.botanibit.outputs.token }}@github.com/".insteadOf "https://github.com/"

    - name: Creating .npmrc
      shell: bash
      if: ${{ inputs.stack == 'npm' || inputs.stack == 'all' }}
      run: |
        echo "@garajonai:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ steps.botanibit.outputs.token }}" >> .npmrc
