name: Load secrets
inputs:
  stack:
    type: choice
    description: 'The stack to run the job on (go, npm, all, none)'
    default: none
    options:
      - go
      - npm
      - all
      - none
  op-token:
    required: true
outputs:
  token:
    value: ${{ steps.botanibit.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Configure 1Password Service Account
      uses: 1password/load-secrets-action/configure@v1.3.2
      with:
        service-account-token: ${{ inputs.op-token }}

    - name: Load Botanibit credentials
      uses: 1password/load-secrets-action@v1.3.2
      with:
        export-env: true
      env:
        APP_ID: "op://Garajonai/Botanibit GH_SVC/App ID"
        PRIVATE_KEY: "op://Garajonai/Botanibit GH_SVC/private key"

    - uses: actions/create-github-app-token@v1
      id: botanibit
      with:
        app-id: ${{ env.APP_ID }}
        private-key: ${{ env.PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Set up Git name and email
      shell: bash
      run: |
        git config --global user.name "botanibit[bot]"
        git config --global user.email ${{env.APP_ID}}+botanibit[bot]@users.noreply.github.com

    - name: Set up Git with token for private go dependencies
      shell: bash
      if: ${{ inputs.stack == 'go' || inputs.stack == 'all' }}
      run: |
        git config --global url."https://x-access-token:${{ steps.botanibit.outputs.token }}@github.com/".insteadOf "https://github.com/"

    - name: Creating .npmrc
      shell: bash
      if: ${{ inputs.stack == 'npm' || inputs.stack == 'all' }}
      run: |
        echo "@garajonai:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ steps.botanibit.outputs.token }}" >> .npmrc
